(() => {
  "use strict";
  const STORAGE_KEY = "shadow_client_settings";
  const DEFAULTS = Object.freeze({fps:true,keystrokes:true,cps:true,fullbright:false,freelook:false,aimAssist:false,autoClicker:false,freelookKey:"AltLeft",menuKey:"ShiftRight",aimMode:"Crosshair",aimRange:4,aimSpeed:3,clickCps:8});
  const LIMITS = Object.freeze({aimRange:[1,32],aimSpeed:[1,10],clickCps:[1,20]});
  const clamp=(n,min,max)=>Math.min(max,Math.max(min,n));
  const validCode=v=>typeof v==="string" && /^[A-Za-z][A-Za-z0-9]*$/.test(v);
  function loadSettings(){try{const saved=JSON.parse(localStorage.getItem(STORAGE_KEY)||"{}");const next={...DEFAULTS,...(saved&&typeof saved==="object"?saved:{})};for(const key of Object.keys(LIMITS))next[key]=clamp(Number(next[key])||DEFAULTS[key],...LIMITS[key]);if(!["Crosshair","Closest","Nearest"].includes(next.aimMode))next.aimMode=DEFAULTS.aimMode;if(!validCode(next.freelookKey))next.freelookKey=DEFAULTS.freelookKey;if(!validCode(next.menuKey))next.menuKey=DEFAULTS.menuKey;return next}catch(_){return {...DEFAULTS}}}
  let settings=loadSettings();const listeners=new Set();let nativeBridge=null;
  function saveSettings(){localStorage.setItem(STORAGE_KEY,JSON.stringify(settings));for(const listener of listeners)listener({...settings});if(nativeBridge)syncNative()}
  function syncNative(){if(!nativeBridge)return;try{if(typeof nativeBridge.setConfig==="function")nativeBridge.setConfig({...settings});if(typeof nativeBridge.setEnabled==="function")for(const mod of ["fullbright","freelook","aimAssist","autoClicker"])nativeBridge.setEnabled(mod,!!settings[mod])}catch(error){console.warn("[Shadow] Native mod bridge rejected settings",error)}}
  const root=document.createElement("div");root.id="shadow-client";root.innerHTML='<div id="shadow-hud" aria-live="polite"></div><section id="shadow-menu" role="dialog" aria-label="Shadow Client settings" aria-hidden="true"><div class="shadow-menu-header"><div><h1>Shadow Client</h1><div class="shadow-subtitle">Lightweight settings for the existing Minecraft 1.8 client</div></div><button id="shadow-close" class="shadow-close" type="button" aria-label="Close">×</button></div><div class="shadow-hint">Right Shift opens this menu. Settings save automatically.</div><div id="shadow-mods"></div></section>';document.body.appendChild(root);
  const hud=root.querySelector("#shadow-hud"),menu=root.querySelector("#shadow-menu"),mods=root.querySelector("#shadow-mods"),closeButton=root.querySelector("#shadow-close");
  function row(name,description){const el=document.createElement("div");el.className="shadow-row";const info=document.createElement("div");info.className="shadow-info";const title=document.createElement("div");title.className="shadow-name";title.textContent=name;const detail=document.createElement("div");detail.className="shadow-description";detail.textContent=description;info.append(title,detail);el.appendChild(info);return {el,info}}
  function addToggle(name,description,setting){const {el}=row(name,description);const button=document.createElement("button");button.type="button";button.className="shadow-button";const update=()=>{const on=!!settings[setting];button.textContent=on?"ON":"OFF";button.classList.toggle("enabled",on);button.setAttribute("aria-pressed",String(on))};button.addEventListener("click",()=>{settings[setting]=!settings[setting];saveSettings();update()});el.appendChild(button);mods.appendChild(el);update()}
  function addNumber(name,description,setting,min,max,step=1){const {el}=row(name,description);const input=document.createElement("input");input.className="shadow-input";input.type="number";input.min=String(min);input.max=String(max);input.step=String(step);input.inputMode="decimal";input.value=String(settings[setting]);const commit=()=>{settings[setting]=clamp(Number(input.value)||DEFAULTS[setting],min,max);input.value=String(settings[setting]);saveSettings()};input.addEventListener("change",commit);input.addEventListener("keydown",event=>{if(event.key==="Enter"){commit();input.blur()}});el.appendChild(input);mods.appendChild(el)}
  function addSelect(name,description,setting,options){const {el}=row(name,description);const select=document.createElement("select");select.className="shadow-select";for(const option of options){const item=document.createElement("option");item.value=option;item.textContent=option;item.selected=option===settings[setting];select.appendChild(item)}select.addEventListener("change",()=>{settings[setting]=select.value;saveSettings()});el.appendChild(select);mods.appendChild(el)}
  function addKeybind(name,description,setting){const {el}=row(name,description);const input=document.createElement("input");input.className="shadow-input shadow-keybind";input.type="text";input.readOnly=true;input.value=settings[setting];input.title="Click, then press a key";input.addEventListener("keydown",event=>{event.preventDefault();event.stopPropagation();if(!event.code||event.code==="Escape")return;settings[setting]=event.code;input.value=event.code;saveSettings();input.blur()});input.addEventListener("click",()=>input.select());el.appendChild(input);mods.appendChild(el)}
  addToggle("FPS Counter","Low-frequency FPS sampling; it does not alter the game loop.","fps");addToggle("Keystrokes","WASD state display with a throttled HUD refresh.","keystrokes");addToggle("CPS Counter","Left-clicks measured over the last second.","cps");addToggle("Fullbright","Uses the native client bridge when available; no CSS brightness filter.","fullbright");addToggle("FreeLook","Preserves the client’s native FreeLook; this layer never moves the camera.","freelook");addKeybind("FreeLook Key","Native key code; default is Left Alt.","freelookKey");addToggle("Aim Assist","Configuration surface for a native target-assist implementation.","aimAssist");addSelect("Aim Target","Target selection mode.","aimMode",["Crosshair","Closest","Nearest"]);addNumber("Aim Range","Maximum target range in blocks.","aimRange",...LIMITS.aimRange,.5);addNumber("Aim Speed","Rotation speed multiplier.","aimSpeed",...LIMITS.aimSpeed,.5);addToggle("Auto Clicker","Configuration surface for a native click implementation.","autoClicker");addNumber("Auto Clicker CPS","Clicks per second, capped to keep the timer lightweight.","clickCps",...LIMITS.clickCps,1);addKeybind("Menu Key","Default is Right Shift.","menuKey");
  let menuOpen=false;function setMenu(open){menuOpen=!!open;menu.style.display=menuOpen?"block":"none";menu.setAttribute("aria-hidden",String(!menuOpen))}closeButton.addEventListener("click",()=>setMenu(false));document.addEventListener("keydown",event=>{if(event.code===settings.menuKey&&!event.repeat){setMenu(!menuOpen);event.preventDefault();event.stopPropagation()}},true);
  const keys=new Set(),clicks=[];document.addEventListener("keydown",event=>keys.add(event.key.toUpperCase()),true);document.addEventListener("keyup",event=>keys.delete(event.key.toUpperCase()),true);document.addEventListener("mousedown",event=>{if(event.button===0)clicks.push(performance.now())},true);
  let frames=0,fps=0,lastFrame=performance.now(),lastHud=0;function sampleFrame(time){frames++;if(time-lastFrame>=500){fps=frames*1000/(time-lastFrame);frames=0;lastFrame=time}if(time-lastHud>=100){lastHud=time;updateHud(time)}requestAnimationFrame(sampleFrame)}
  function updateHud(now=performance.now()){const cutoff=now-1000;while(clicks.length&&clicks[0]<cutoff)clicks.shift();hud.replaceChildren();if(settings.fps){const box=document.createElement("div");box.className="shadow-hud-box";box.textContent="FPS: "+Math.round(fps);hud.appendChild(box)}if(settings.keystrokes){const box=document.createElement("div");box.className="shadow-hud-box";const keyboard=document.createElement("div");keyboard.id="shadow-keystrokes";for(const key of ["","W","","A","S","D"]){const item=document.createElement("div");item.className="shadow-key";item.textContent=key;if(key&&keys.has(key))item.classList.add("active");keyboard.appendChild(item)}box.appendChild(keyboard);if(settings.cps){const cps=document.createElement("div");cps.className="shadow-cps";cps.textContent="CPS: "+clicks.length;box.appendChild(cps)}hud.appendChild(box)}else if(settings.cps){const box=document.createElement("div");box.className="shadow-hud-box";box.textContent="CPS: "+clicks.length;hud.appendChild(box)}}
  window.ShadowClient={getSettings:()=>({...settings}),isEnabled:mod=>!!settings[mod],getAimSettings:()=>({mode:settings.aimMode,range:settings.aimRange,speed:settings.aimSpeed}),getAutoClickerSettings:()=>({enabled:settings.autoClicker,cps:settings.clickCps}),getKeybinds:()=>({freelook:settings.freelookKey,menu:settings.menuKey}),isFreeLookActive:()=>!!(nativeBridge&&typeof nativeBridge.isFreeLookActive==="function"&&nativeBridge.isFreeLookActive()),onSettingsChanged:listener=>{listeners.add(listener);return()=>listeners.delete(listener)},attachNativeBridge:bridge=>{nativeBridge=bridge&&typeof bridge==="object"?bridge:null;syncNative()},saveSettings};
  const bridgeProbe=window.ShadowNativeMods;if(bridgeProbe)window.ShadowClient.attachNativeBridge(bridgeProbe);setMenu(false);updateHud();requestAnimationFrame(sampleFrame);
})();